### PR TITLE
Fix overriding of prometheus scrape

### LINKED ISSUE #621: Allow Prometheus scraping annotation to be specified
## Expected Behaviour

```
faas-cli store deploy figlet --annotation prometheus.io.scrape=true --annotation prometheus.io.port=8081
```

This should result in an annotation of `prometheus.io.scrape=true` being assigned to the Deployment, but it does not.

## Current Behaviour

The following shows it as `false:

```
kubectl get deploy -n openfaas-fn figlet -o yaml
```

## Possible Solution

I'm guessing that it's hard-coded to be false.

## Steps to Reproduce (for bugs)

0. `kind create`
1. `arkade install openfaas`
2. `faas-cli store deploy figlet --annotation prometheus.io.scrape=true --annotation prometheus.io.port=8081`

## Context

This will be required for the tutorial on custom_metrics scaling: https://github.com/openfaas/docs/issues/173

### PR DESCRIPTION
**Pull request by Waterdrips**
## Description

The prometheus.io.scrape annotation was being overridden in faas-netes
if it was set. This means a user could never set it to true for a
functtion using something like faas-cli store deploy figlet --annotation
prometheus.io.scrape=true

Signed-off-by: Alistair Hey <alistair.hey@form3.tech>

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
fixes #621 

## How Has This Been Tested?

This was tested by writing unit tests to validate that the operator did
not do the same thing and writing a new test for faas-netes's deployment
handler to check that if its set, its not overridden.

Then tested on k3d, using:
1) k3d create
2)arkade install openfaas
3) set the faas-netes container to the one created from this commit
4) faas-cli store deploy figlet --annotation prometheus.io.scrape=true
5) validate that the annotation was not overridden (kubectl get deploy
-n openfaas-fn figlet -o yaml)
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Waterdrips** [comment]
if merged this would need:

* new faas-netes container build
* chart faas-netes version bump and chart release

File: handlers/deploy_test.go [hunk 1]
```diff
@@ -32,6 +32,25 @@ func Test_buildAnnotations_Empty_In_CreateRequest(t *testing.T) {
 	}
 }
 
+func Test_buildAnnotations_Premetheus_NotOverridden(t *testing.T) {
```
Comment (alexellis) [inline handlers/deploy_test.go:35]: Have we got a test for the default usecase too?

Comment (Waterdrips) [reply handlers/deploy_test.go:35]: yes, the test that already exists covers the default already.

Comment (Waterdrips) [reply handlers/deploy_test.go:35]: https://github.com/openfaas/faas-netes/blob/b733782ad4953ec0bf9e6e450cd8e25ab0ae0651/handlers/deploy_test.go#L16-L33

File: handlers/deploy_test.go [hunk 2]
```diff
@@ -32,6 +32,25 @@ func Test_buildAnnotations_Empty_In_CreateRequest(t *testing.T) {
...
+	request := types.FunctionDeployment{Annotations: &map[string]string{"prometheus.io.scrape": "true"}}
+
+	annotations := buildAnnotations(request)
+
+	if len(annotations) != 1 {
+		t.Errorf("want: %d annotations got: %d", 1, len(annotations))
```
Comment (alexellis) [inline handlers/deploy_test.go:41]: You could probably add a return there, or use `t.Fatalf` that @LucasRoesler introduced me to, which returns out of the test. 

Also extract `"true"` to `want := "true"` please. 

I'll merge, but send in the alteration after.
