### PR TITLE
Reduce the readiness checks for functions

### LINKED ISSUE #218: Use the /healthz endpoint to provide a more accurrate readiness check
The existing behavior of checking for the existence of /tmp/.lock does indeed verify that the container is up, but does not accurately validate the function is ready to receive requests.

The /healthz endpoint should provide a better mechanism for actual readiness

## Expected Behaviour

The kubernetes readiness and liveliness check should make an http request to the existing healtz endpoint of the function pod.

## Current Behaviour

The readiness and liveliness check simply check for the existence of a file /tmp/.lock

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distriubtion of Kubernetes are you using? `kubectl version`

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

### PR DESCRIPTION
**Pull request by berndtj**
* Significantly improves scale up time for functions (when going
  from 0 -> 1)
* Health check is hit more frequently, but should not noticibly
  impact performance
* Use the httpget probe type and leverage the watchdog /healthz
  endpoint

This could be optimized a little further if new image for doing
the http probes where created which would block on connection errors
and return immediately when the response comes back, but the best
case is < 1s improvement.

Some performance numbers.  Before (there was a timeout error):

cold start: 10.240251064300537
error calling function: Command 'echo -n "Test" | faas-cli -g http://192.168.64.78:31112 invoke hello-python' returned non-zero exit status 1.
cold start: 4.621361255645752
cold start: 5.6364970207214355
cold start: 11.648431777954102
cold start: 8.450724840164185
cold start: 9.854270935058594
cold start: 12.048357009887695
cold start: 12.24026870727539

After:

cold start: 1.8590199947357178
cold start: 1.8544681072235107
cold start: 2.065181016921997
cold start: 1.8414137363433838
cold start: 1.6598482131958008
cold start: 2.4577977657318115
cold start: 2.4510068893432617
cold start: 2.244048833847046
cold start: 2.6444039344787598

## Motivation and Context

Fix #218

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

```
import requests
import subprocess
import time

for i in range(10):
    now = time.time()
    try:
        subprocess.check_output('echo -n "Test" | faas-cli -g http://192.168.64.78:31112 invoke hello-python', shell=True)
        print("cold start: %s" % (time.time() - now))
    except Exception as e:
        print("error calling function: %s" % e)
    resp = requests.post("http://192.168.64.78:31113/system/scale-function/hello-python", json={"serviceName": "hello-python", "replicas": 0})
    time.sleep(10)
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

This only breaks very old functions which use a version of the watchdog which does not have a /healtz endpoint

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: handlers/deploy.go [hunk 1]
```diff
@@ -118,16 +116,19 @@ func MakeDeployHandler(functionNamespace string, clientset *kubernetes.Clientset
 
 func makeDeploymentSpec(request requests.CreateFunctionRequest, existingSecrets map[string]*apiv1.Secret, config *DeployHandlerConfig) (*v1beta1.Deployment, error) {
 	envVars := buildEnvVars(&request)
-	path := filepath.Join(os.TempDir(), ".lock")
 	probe := &apiv1.Probe{
 		Handler: apiv1.Handler{
-			Exec: &apiv1.ExecAction{
-				Command: []string{"cat", path},
+			HTTPGet: &apiv1.HTTPGetAction{
```
Comment (alexellis) [inline handlers/deploy.go]: This can't be turned on by default, it needs to be optional.

File: handlers/deploy.go [hunk 2]
```diff
@@ -118,16 +116,19 @@ func MakeDeployHandler(functionNamespace string, clientset *kubernetes.Clientset
...
+				Path: "/healthz",
+				Port: intstr.IntOrString{
+					Type:   intstr.Int,
+					IntVal: int32(watchdogPort),
+				},
 			},
 		},
-		InitialDelaySeconds: 3,
+		InitialDelaySeconds: 0,
```
Comment (alexellis) [inline handlers/deploy.go]: Please introduce a configuration item for this. You can largely copy and paste from the existing variables.

Should also be available via helm as an option.

File: handlers/deploy.go [hunk 3]
```diff
@@ -118,16 +116,19 @@ func MakeDeployHandler(functionNamespace string, clientset *kubernetes.Clientset
...
 		TimeoutSeconds:      1,
-		PeriodSeconds:       10,
+		PeriodSeconds:       1,
```
Comment (alexellis) [inline handlers/deploy.go]: This should also be a configuration item with a default of the previous value for compatibility. When used in dispatch you'd just set your values via the helm chart

File: handlers/deploy.go (hunk 1 above)
Comment (berndtj) [reply handlers/deploy.go]: Oh, I had thought based on our off-line conversation this wasn't the case.  Easy to make optional

File: handlers/deploy.go (hunk 2 above)
Comment (berndtj) [reply handlers/deploy.go]: ok

File: handlers/deploy.go (hunk 3 above)
Comment (berndtj) [reply handlers/deploy.go]: Are you sure you want the default to be the previous value(s)?  These values will have far more positive effect than negative, and shouldn't break anything existing

**Comment by berndtj** [comment]
Yes @alexellis I assumed any change to the actual probe, would be a separate PR

**Comment by berndtj** [comment]
Pretty much exposed everything.  Let me know if you think this is going a bit far.  Also, I left the default for the liveness probe the same as before, but the readiness probe has new values which make 0->1 scaling faster.

**Comment by alexellis** [comment]
Hi @berndtj that is very thorough work, thanks for taking time to think through the configuration options and for signing-off the PR.

Here is what I was thinking:

Since we use the same-point for liveness and readiness, they should always be enabled, but the question is which mode. Compatibility mode or http-mode?

```
   probe_type: http 
```

```
   probe_type: lock 
```

Both are needed to keep compatibility with existing functions, that's why the option is needed.

Given a value of `http` then the `/_/health` endpoint should be queried (as defined in the watchdog). The OpenFaaS watchdog uses a prefix to avoid any clashing of function endpoints:

```
/_/health
```

https://github.com/openfaas/faas/blob/master/watchdog/main.go#L53

faas-netes and the gateway expose health via `/healthz` because they are not functions, but services.

If you are not using the watchdog and don't want to expose your health endpoint via `/_/health` then perhaps this should be configurable in the helm chart, for your use only?

Given a value of `lock` then the existing code should still run and the `http` probe should not be added.

I think we could de-duplicate the options in the PR and use the same values for timeout / period checking and initial check for both liveness and readiness. At this stage they point at the same endpoint and react in the same way.

What are your thoughts on above?

**Comment by berndtj** [comment]
That's kind of embarrassing (/healthz vs /_/health).  I'm surprised it still passes readiness/liveness.  I'm not sure the value needs to be configurable necessarily.

Anyway on to your other points.  Yeah, I forgot about "compatiblity" mode, that's easy enough.

I explicitly did not dedupe the probes as I figured you actually want different values for liveness and readiness even if the endpoint is the same.  For instance, I can live with a much longer period with liveness, but I want as short as possible for readiness.

**Comment by berndtj** [comment]
Yes, I only see it scaling from 0->1 (but to be honest I'm not testing subsequent requests).  We've also seen it with Dispatch and openfaas when we are waiting on the function to become ready.  It's likely the same issue.

I actually have a change to the actual readiness check that doesn't rely on the lock file at all.  I'll give that a test.  I think it actually does fix the issue.

File: types/read_config.go [hunk 4]
```diff
@@ -92,9 +108,15 @@ func (ReadConfig) Read(hasEnv HasEnv) BootstrapConfig {
 
 // BootstrapConfig for the process.
 type BootstrapConfig struct {
-	EnableFunctionReadinessProbe bool
-	ReadTimeout                  time.Duration
-	WriteTimeout                 time.Duration
-	ImagePullPolicy              string
-	Port                         int
+	HTTPProbe                         bool
```
Comment (alexellis) [inline types/read_config.go]: Think this might be useful to comment on:

```
// HTTPProbe when set to true switches readiness and liveness probe to access /_/health over HTTP instead of accessing /tmp/.lock.
```

File: types/read_config.go [hunk 5]
```diff
@@ -92,9 +108,15 @@ func (ReadConfig) Read(hasEnv HasEnv) BootstrapConfig {
...
+	ReadinessProbeInitialDelaySeconds int
+	ReadinessProbeTimeoutSeconds      int
+	ReadinessProbePeriodSeconds       int
```
Comment (alexellis) [inline types/read_config.go]: Curious if this is worth making a Golang duration in this PR or a follow-up?

The other configs support Golang durations now, could call `durationVal.Seconds()` in the code to convert if that makes sense.

File: chart/openfaas/templates/gateway-dep.yaml [hunk 6]
```diff
@@ -113,6 +113,20 @@ spec:
           value: "{{ .Values.faasnetesd.writeTimeout }}"
         - name: image_pull_policy
           value: {{ .Values.faasnetesd.imagePullPolicy | quote }}
+        - name: http_probe
```
[the remark this answers is not in the document]
Comment (alexellis) [reply chart/openfaas/templates/gateway-dep.yaml]: (Just seen the defaults in the code, if the defaults work well then we could update the YAML later.) Best way to test is to `kubectl delete` the two OpenFaaS namespaces, then apply the YAML folder again.

File: types/read_config.go (hunk 5 above)
Comment (alexellis) [reply types/read_config.go]: I don't consider this as compulsory - just want your take on it.

**Comment by berndtj** [comment]
I hadn't even considered the yaml ;).  I'll make sure and test first

File: handlers/deploy.go [hunk 7]
```diff
@@ -118,21 +127,41 @@ func MakeDeployHandler(functionNamespace string, clientset *kubernetes.Clientset
 
 func makeDeploymentSpec(request requests.CreateFunctionRequest, existingSecrets map[string]*apiv1.Secret, config *DeployHandlerConfig) (*v1beta1.Deployment, error) {
 	envVars := buildEnvVars(&request)
-	path := filepath.Join(os.TempDir(), ".lock")
-	probe := &apiv1.Probe{
-		Handler: apiv1.Handler{
+	var handler apiv1.Handler
+
+	if config.HTTPProbe {
```
Comment (stefanprodan) [inline handlers/deploy.go]: This looks good for now but in the future we should have a way to switch this flag from the function definition so that is backwards compatible with functions that are built with the old watchdog.

File: types/read_config.go [hunk 8]
```diff
@@ -92,9 +108,15 @@ func (ReadConfig) Read(hasEnv HasEnv) BootstrapConfig {
...
+	LivenessProbeInitialDelaySeconds  int
+	LivenessProbeTimeoutSeconds       int
+	LivenessProbePeriodSeconds        int
```
Comment (stefanprodan) [inline types/read_config.go]: I would make these of type `time.Duration` but we can address this at a later time.

File: handlers/deploy.go (hunk 7 above)
Comment (alexellis) [reply handlers/deploy.go]: For instance, we could use the new annotations field being worked on by @ewilde

**Comment by alexellis** [comment]
Not going to be popular for saying this, but we've had some Chart changes merged since the PR.

This generally means resetting the commit, rebasing the chart then running make charts again before doing a commit with a force.

Other than that LGTM.

Alex

**Comment by alexellis** [comment]
Hi Berndt I know you have time away coming up, all I could do at this point is to take your commit, reset it, fix it and add it back again but it would lose your authorship. I could perhaps set the "git author" but it won't look like it does now in the history.

Alex

**Comment by berndtj** [comment]
I can fix it up right now.

**Comment by alexellis** [comment]
We just discovered the tests were broken in this commit, fixed in #249.

**Comment by dkozlov** [comment]
Hi @berndtj,  Do you have plans to add /_/health endpoint in https://github.com/openfaas-incubator/of-watchdog functions?

**Comment by alexellis** [comment]
This is the wrong repo for the question. There's already a disk-based health check with s http one in progress - https://github.com/openfaas-incubator/of-watchdog/pull/13
